### ISSUE TITLE
Telegram uses sdcard0 instead of sdcard1

### ISSUE THREAD

**Issue by Techwolf** [slp/Telegram-FOSS#100]
Most phones/tablets had limited internal storage. The wiki here, http://telegram.wiki/tips:androidcache , says "|-- sdcard0 or sdcard1 (depends on phone)". On my device, sdcard0 is only 4GB while sdcard1 is 64GB. However, telegram uses sdcard0 and chews up over 2GB there. I need to move and set telegram to use sdcard1 instead.

**Comment by slp** [comment]
This enhancement is beyond this project's purpose.
