### ISSUE TITLE
Messages are not received anymore

### ISSUE THREAD

**Issue by c33s** [slp/Telegram-FOSS#103]
current foss telegram version is ´3.7.0 (767) universal´, according a friend of mine the official telegram version is ´3.10.1 (821) arm-v7a´
it looks like the version difference is too high, since today i am not receiving messages anymore.

in the chat overview, the person who wrote to me is listed to the first place, i can see the first few words of the message but i don't get a message notification sound and if i go in the chat of the person who wrote me, there is no new message.

if i am in the chat while a person is writing to me, i get the message (i thing most of the time but not everytime but i have to check that again)

**Comment by c33s** [comment]
maybe realated to:
https://github.com/slp/Telegram-FOSS/issues/102
https://github.com/slp/Telegram-FOSS/issues/92

**Comment by slp** [comment]
3.10.1 is already on F-Droid.
