### ISSUE TITLE
Import/Export Feature (Backup)

### ISSUE THREAD

**Issue by c33s** [slp/Telegram-FOSS#104]
it would be awesome to have a simple, as for me, plain text import/export function, to backup all my chats and their content (text, images,..).
would make it easier to test beta versions

**Comment by c33s** [comment]
import/export from all usernames would also awesome (for people like me, who block the app from accessing the addressbook)

**Comment by slp** [comment]
Sorry, but this enhancement is outside the scope of this project.

**Comment by alexanderadam** [comment]
Is there any other possibility to make a full backup of Threema without having to have `root` access on the device?
