### ISSUE TITLE
Reply in-notification

### ISSUE THREAD

**Issue by DavidJacobson** [slp/Telegram-FOSS#105]
This is a feature request - apps like Whatsapp allow you to reply to a message by hitting a little reply button on the notification, which creates a small window so you can respond without fully launching the app. This saves time, and I think it would be a good feature. 

[more info](http://gadgets.ndtv.com/apps/news/whatsapp-for-android-update-adds-quick-replies-from-notifications-819235)

**Comment by slp** [comment]
Sorry, but this enhancement is outside the scope of this project. Ask upstream.
