### ISSUE TITLE
for telegram people: use address book photo when no telegram photo

### ISSUE THREAD

**Issue by landry314** [slp/Telegram-FOSS#106]
Sorry to post this here but since Telegram wont receive bug reports, I don't know where else to post it... maybe we should create a new github just for them and hope they look at it.

I collected many contact photos in my address book but Telegram doesn't use them. If someone has no photo set in telegram then it is just blank. It would be wonderful if Telegram would copy the set of contact photos in the normal address book into its own address book so if no photo is set on the server then the local photo will be used instead. I want to be able to add my own photos for contacts if they haven't set one... or maybe even if they already have. A setting could be added "Use local contact photos instead" with a sub setting "Only if one is not set by user". Wouldn't that be nice?

**Comment by slp** [comment]
Sorry, but this enhancement is outside the scope of this project. Ask upstream.

**Comment by Salkin2** [comment]
@slp
Well, that changes things a lot then... I think many of us hadn't understood well this project. According with waht you say it's not related at all with official Telegram, right? I think many of us just believed that TG FOSS was just a FOSS version made by, or ar least supervised, the official Telegram developers who also make the "proprietary friendly" version.

So, if you have no relation with TG would you mind to tell us how to contact them in an interactive way like this in Github? In https://telegram.org/faq#telegram-support they only provide some Twitter accounts, which is obviously a defficient platform to report bugs, ask stuff or propose features, and besides is very probable that FOSS users don't have an account in a proprietary platform like that.
So, if you know were users could contact them, I think most of us would be very grateful, besides stop annoying you with issues that are out of your scope.

**Comment by Bubu** [comment]
We have no other way of contacting them then what is stated in the faq link you posted. Which means there is basically no communication at all. Sorry.

**Comment by Bubu** [comment]
The in app support might work best. There is a lot of documentation on the Telegram site how the volunteers should escalate bug reports they receive via the in app support chat to the telegram ticketing system (which is not public).

**Comment by Salkin2** [comment]
@Bubu Damn! :-/ Server's code not released almost 3 years after they said it would be released "soon", no interactive communication with users... They have a peculiar conception of community between developers and users that if habitual in open source software. :(

Thanks anyway for you information +1:

**Comment by landry314** [comment]
i agree. having trouble trusting telegram anymore... i recommend using signal with gmscore or libresignal... signal is water tight and more transparent.

as for communicating with telegram, i used their built in help and got a great volunteer who was very helpful and took all my suggestions. i think it is hit or miss with their help system.
