### ISSUE TITLE
How to keep up to date to latest version

### ISSUE THREAD

**Issue by jinformatique** [slp/Telegram-FOSS#114]
Hi, recently I was happy to see Telegram v 3.10.1 coming to F-Droid after months stuck with v 3.7.0.
But on the play store there is already a new version now. How is it possible to keep up to date on a regular basis? Could someone share a tuto on how to do all the steps to bring latest version on F-Droid?
Many thanks.

**Comment by Peque** [comment]
First, you need the source code from upstream (note that only 3.10.1 is currently available):

https://github.com/DrKLO/Telegram/commits/master

Upstream Android application development does not seem very transparent/friendly... :sweat:

However, I would also be interested in a "tutorial" on how to create a FOSS version out of the upstream version. I guess @slp is the one to ask here, in case he has the time, will and generosity to create it. :wink:

PS: @slp, have you considered a campaing on BountySource?

**Comment by aurium** [comment]
Any idea when @DrKLO will publish Telegram 3.13?

**Comment by Peque** [comment]
That, only @DrKLO knows... :disappointed: 

On the other hand, I think not releasing the code is actually a license violation, as Telegram Android client is under the GPL. Feel free to ask the Telegram organization/support, by any means, and tell us if you get any response.

**Comment by aurium** [comment]
The Telegram APK at GooglePlay is released under GPL?

**Comment by Peque** [comment]
@aurium The [Android client is under the GPL](https://github.com/DrKLO/Telegram/blob/master/LICENSE), yes. So, as long as i understand it, @DrKLO should be publishing the source code along with the APK distributed in Google Play.

**Comment by lillet23** [comment]
Source code for version 3.13.1 was published yesterday ;-)

**Comment by nachoparker** [comment]
I would also be interested in knowing the steps / features that were changed from upstream.
It would be a first step for gathering more help on this awesome fork and offload some work from @slp 

I would like to offer some help, time permitting, to try keep up with the releases.

**Comment by aurium** [comment]
As we read in `README.md `, this project makes minimal changes to original source to remove proprietary dependencies. Questions:

1. Is it automated in some way?
2. How easy is to make this changes a compilation option? _(allowing this project to submit patches to @DrKLO and reduce the release effort)_

**Comment by vanitasvitae** [comment]
I'd appreciate a "guide" as well. I imagine it would be quite nice for the maintainers of this repo if other people could create PRs that strip off unfree dependencies instead of having to do it all on their own ;) At the moment nobody can really help (I'm sure many people would, if there was a guide how)

**Comment by slp** [comment]
Syncing changes from upstream is not trivial work, and can't be automated. It requires knowledge of Java, Android SDK and its tools, C and C++.

Every update is different, ranging from the ones that require only minor fixes, to huge ones like replacing boringssl or fixing ffmpeg compilation.
