### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by ymhuang0808** [slp/Telegram-FOSS#117]
The upstream Telegram supports a few languages. Could I create a pull request for Traditional Chinese in the project?

**Comment by Ecron** [comment]
The upstream Telegram project support language packs. You can get them from Transifex, if the app is fully translated to your language, or join the translation teams and contribute translating Telegram to your own languange. You have more info here: https://www.transifex.com/telegram/

**Comment by slp** [comment]
Thanks for the answer @Ecron

**Comment by JimmyS83** [comment]
@Ecron not for all cases I am afraid :(  I made Czech language packs for all Desktop, Android and Web versions, but for some reasons I cant ask for that language @Transifex, also I cant request join the team (Czech language are not in list). 

Transifex told me, that I need to solve this with admins of Telegram@Transifex, but they kind of ignoring me on Telegram / emails / Transifex mail. I also make PR to that, as I just cant access Transifex nor did there anything. 

Its kinda furstrating, as I spent many hours with translation, Telegram would only benefit from this, with minimal/no effort, but for some reason they do not respond at all.

**Comment by Ecron** [comment]
That's true, @JimmyS83, they stopped accepting new languages some time ago. However, Pavel Durov announced some kind of "revolutionary platform" coming soon, you can check it in [this link](https://twitter.com/durov/status/847764487713239040).

Maybe after they release it we can enjoy a more open translation platform (I really wish). You can join the [Telegram News Channel](t.me/telegram) to be informed about the latest news.

**Comment by JimmyS83** [comment]
Thanks for a hints! I joined telegram news channel, didnt notice it at all. Today I got the first official answer from one of telegram's developers (Desktop):

> The localization approach will be changed in a month or two. For now no more official languages is added, but with the new localization system there will be a way to add all existing languages.

So, lets hope for the best.
