### ISSUE TITLE
Error in build 

### ISSUE THREAD

**Issue by appendhc** [slp/Telegram-FOSS#123]
In file included from D:/f/foss/TMessagesProj//jni/./jni.c:7:0:
D:/f/foss/TMessagesProj//jni/openssl/include/openssl/aes.h:1:1: error: expected identifier or '(' before '.' token
 ../../crypto/aes/aes.h
 ^
In file included from c:\users\administrator\appdata\local\android\sdk\ndk-bundle\platforms\android-9\arch-arm\usr\include\sys\time.h:33:0,
                 from c:\users\administrator\appdata\local\android\sdk\ndk-bundle\platforms\android-9\arch-arm\usr\include\sys\select.h:32,
                 from c:\users\administrator\appdata\local\android\sdk\ndk-bundle\platforms\android-9\arch-arm\usr\include\unistd.h:34,
                 from D:/f/foss/TMessagesProj//jni/./jni.c:8:
c:\users\administrator\appdata\local\android\sdk\ndk-bundle\platforms\android-9\arch-arm\usr\include\linux\time.h:48:18: error: field 'it_interval' has incomplete type
  struct timespec it_interval;
                  ^
c:\users\administrator\appdata\local\android\sdk\ndk-bundle\platforms\android-9\arch-arm\usr\include\linux\time.h:49:18: error: field 'it_value' has incomplete type
  struct timespec it_value;
                  ^
D:/f/foss/TMessagesProj//jni/./jni.c: In function 'Java_org_telegram_messenger_Utilities_aesIgeEncryption':
D:/f/foss/TMessagesProj//jni/./jni.c:47:5: error: unknown type name 'AES_KEY'
     AES_KEY akey;
     ^
D:/f/foss/TMessagesProj//jni/./jni.c:50:60: error: 'AES_DECRYPT' undeclared (first use in this function)
         AES_ige_encrypt(what, what, length, &akey, ivBuff, AES_DECRYPT);
                                                            ^
D:/f/foss/TMessagesProj//jni/./jni.c:50:60: note: each undeclared identifier is reported only once for each function it appears in
D:/f/foss/TMessagesProj//jni/./jni.c:53:60: error: 'AES_ENCRYPT' undeclared (first use in this function)
         AES_ige_encrypt(what, what, length, &akey, ivBuff, AES_ENCRYPT);
                                                            ^
make: *** [D:\f\foss\TMessagesProj\/obj/local/armeabi/objs/tmessages.24/./jni.o] Error 1

**Comment by FloGatt** [comment]
Push. Have the same problem.

**Comment by Bubu** [comment]
What @FloGatt said, symlink problem on Windows.
