### ISSUE TITLE
Updated source

### ISSUE THREAD

**Issue by JonnyTech** [slp/Telegram-FOSS#128]
Play Store hosts version 3.16 but sources not available, can they be released so F-droid repo be updated?

**Comment by Findus23** [comment]
It doesn't seem like they published the source yet: https://github.com/DrKLO/Telegram/commits/master

**Comment by JonnyTech** [comment]
Thanks, I had noticed, hence why I asked...

**Comment by slp** [comment]
While I'm going to continue updating Telegram-FOSS (for a while, at least) as a courtesy to its current users, if you really care about Free Software and/or privacy, you should seriously consider switching to a fully open (protocol, server and client), federated alternative, like Matrix/Riot (https://matrix.org).

I've done that myself, deploying my own HomeServer, and couldn't be happier (also features voice and video calls).

**Comment by krt16s** [comment]
@slp did you contact upstream about this? We are already several versions behind, so it would be nice to know if Telegram is going to publish sources or if they decided to go fully proprietary. If that's the case, I will move telegram to fdroids archive.

In any case, thanks so much for going through the hassle and maintaining a floss build flavor. It was a pleasure working with you (despite it being fully automated  by now ;)).

**Comment by Bubu** [comment]
@krt16s Well upstream is pretty much deaf regarding the Telegram android version. Until now the code always dropped at some point.

But regardless of this I and several of my colleagues/friends/family still use the Telegram fdroid version, which continues to work flawlessly. 

I don't know what is the policy of archiving an app in fdroid but for now I see no reason to do so.

**Comment by krt16s** [comment]
@Bubu If there wont be any new floss release, moving to the archive will remove it from the mainline repository, so new users dont get "tricked" into installing it. Existing users should have the latest available nonetheless. Also: If you need to reinstall, you can always grab the latest fdroid build from the archive repo -- either by enabling it in the client or directly via http.

**Comment by Bubu** [comment]
@krt16s Apparently there will be updated source code at some point: https://github.com/DrKLO/Telegram/commit/64e8ec3fbd26a876b7683f83a6f59c6b67316421#commitcomment-20673338

**Comment by Bubu** [comment]
Earlier today I was at the matrix.org talk at FOSDEM [1] and was really, really impressed. 

While I like the Telegram Clients and most of their features, project management of the android app is absolutely terrible. :-(

In theory matrix allows you to keep talking to all of your Telegram contacts (and most other chat services) while being connected to your own self-hosted matrix server using any matrix client. Let's see how good this is in practice :-).

I can definitely recommend watching the FOSDEM recording explaining all this and also the crypto behind it, when it's live in a day or so!

[1] https://fosdem.org/2017/schedule/event/encrypting_matrix/

**Comment by Mikaela** [comment]
The current version of Telegram seems to be [3.17.0](https://www.apkmirror.com/apk/telegram-messenger-llp/telegram/) and Telegram

> is a free and open platform – for stickers, for bots, and even for third-party client apps. We believe that if we give you freedom, you’ll know what to do with it. 

via https://telegram.org/blog/android-themes

**Comment by JonnyTech** [comment]
The latest on f-droid is 3.13.1 (https://f-droid.org/repository/browse/?fdid=org.telegram.messenger)

**Comment by Technowix** [comment]
Make foss great again !

**Comment by mastad0n** [comment]
Anything we can do to make 3.17 happen? Thank you for your hard work!

**Comment by Bubu** [comment]
@mastad0n Keep bothering Telegram to release the Android source code. They haven't released any code in half a year :-(.

Maybe try talking to them on twitter/support channels, maybe try complaining directly to the Durov: https://twitter.com/durov

**Comment by mastad0n** [comment]
Thanks @Bubu will do!

**Comment by danialbehzadi** [comment]
It has been released: https://github.com/slp/Telegram-FOSS/issues/131

**Comment by Bubu** [comment]
Closing in favor of #131
