### ISSUE TITLE
Execution failed for task ':TMessagesProj:externalNativeBuildX86Debug'

### ISSUE THREAD

**Issue by gooddeveloper2107** [slp/Telegram-FOSS#130]
i try to run DRkLo project plz help me:

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':TMessagesProj:externalNativeBuildX86Debug'.
> Build command failed.
Error while executing process C:\android-ndk-r14b\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Gooddeveloper\.AndroidStudio2.3\Telegram-master\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Gooddeveloper\.AndroidStudio2.3\Telegram-master\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=C:/Users/Gooddeveloper/.AndroidStudio2.3/Telegram-master/TMessagesProj/build/intermediates/ndkBuild/x86/debug/obj NDK_LIBS_OUT=C:\Users\Gooddeveloper\.AndroidStudio2.3\Telegram-master\TMessagesProj\build\intermediates\ndkBuild\x86\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 C:/Users/Gooddeveloper/.AndroidStudio2.3/Telegram-master.
make (e=87): The parameter is incorrect.
.
.
.

  make: *** [C:/Users/Gooddeveloper/.AndroidStudio2.3/Telegram-master/TMessagesProj/build/intermediates/ndkBuild/x86/debug/obj/local/x86/libtmessages.24.so] Error 87

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by bbincybbaby** [comment]
am having same issue

**Comment by Bubu** [comment]
Can't help you here. I'm only building on linux and it works out of the box with the NDK. (Only thing we might need to change is the signing config.)

**Comment by PattyGeorgi** [comment]
hi @gooddeveloper2107 were you able to fix this problem? i'm facing the same problem at the moment and i can't figure out how to fix it.

**Comment by bbincybbaby** [comment]
i have fixed this error for 3.18.1

**Comment by PattyGeorgi** [comment]
@bbincybbaby how did you fix it?

**Comment by omegasoft7** [comment]
I had the same issue and i could resolve it with changing my Build Variant to "fatFoss" :D

**Comment by alifetrati** [comment]
hi how to run below code in android studio:
git submodule update --init --recursive

**Comment by alifetrati** [comment]
i have this problem in android studio and i cant resolve this.
@bbincybbaby how to fix this error?

**Comment by imran-samed** [comment]
its not working for me

**Comment by alifetrati** [comment]
just use version 12 of ndk

**Comment by thealpha** [comment]
I am facing same problem guys
anyone please help me

**Comment by Try64** [comment]
Still not working in 2019
