### ISSUE TITLE
Merge 2.3.0

### ISSUE THREAD

**Issue by stefan-niedermann** [slp/Telegram-FOSS#23]
v. 2.3.0
- Sticker-Testphase: Hinter ausgewählten Emoji verstecken sich bereits einige Sticker. Viele weitere werden folgen.
https://telegram.org/blog/stickers
All stickers: https://telegram.org/blog/stickers-meet-art-and-history
v. 2.2.0
- Bilder und GIFs online suchen und verschicken.

**Comment by slp** [comment]
Just merged 2.3.2. This took a while, because I had to remove another intrusive feture (Bing/Giffy search).
