### ISSUE TITLE
On 2.5.2 impossible to share location

### ISSUE THREAD

**Issue by sevan6** [slp/Telegram-FOSS#27]
Hi

With version 2.5.2 during a chat, the location sharing does not work : the option is displayed when selecting the paperclip to attach things but selecting 'location' has no effects. 
Gps is on. 

On a friend's device it works but it is the Google Play version, not F-Droid. 

I have not installed Google Services but I think it should be independant. 

Keep up the good work, 
Sevan

**Comment by slp** [comment]
On Telegram's implementation, location sharing depends on Google Maps and, by extension, on Google Services. For this reason, that functionality is completely removed from Telegram-FOSS (it doesn't matter wether you have Google Services installed or not).

The good thing about this, is that it allows us to remove the permissions related to location services, which makes running the app a bit more secure.

**Comment by stefan-niedermann** [comment]
hm. how much effort would it be, to replace GMaps with an OSM implementation? Would it be too much work for you?

**Comment by sevan6** [comment]
@slp Thanks for your quick answer.
Makes sense in the FOSS implementation and frankly it is not a feature I miss. I noticed the different behaviour with other versions. Now I know why :)
So it is OK on my side.

I keep this item open if you want to consider the suggestion of @stefan-niedermann 
Feel free to close it as soon as you think it is appropriate.

Thanks again and keep up the great work!

**Comment by TameOfGroans** [comment]
You very likely do NOT need G "services". Have you tried the alternative to G services for location?  

search F-droid for: nlp 


you'll need to install at least two apps. faq available

**Comment by TameOfGroans** [comment]
OT: ^ an option I prefer for most every scenario is creation of device local database correlating wifi ap mac and GNSS.  As OT this does not fit your use case. The many NLP offerings DO provide location resolution for your use case.

**Comment by slp** [comment]
Do you know of any free software Android applications which integrate OSM? I'd like to take a look.

**Comment by stefan-niedermann** [comment]
this sounds great :) well, for example osmand can use OSM (it's available on f-droid, too):
http://osmand.net/
https://github.com/osmandapp/Osmand

**Comment by TameOfGroans** [comment]
https://github.com/siacs/Conversations/issues/1069 

https://github.com/siacs/ShareLocationPlugin

**Comment by wp9015362** [comment]
Probably related to:

https://github.com/DrKLO/Telegram/issues/1060

**Comment by mikelglez** [comment]
Maybe this library could help https://github.com/osmdroid/osmdroid (I didn't know this version of Telegram so I'll quit the official client) :D

**Comment by vanitasvitae** [comment]
I thought, GuardianProjects LocationPrivacy was causing the problem. Why don't you remove the option to share location untill this feature works?

**Comment by emunicio** [comment]
The integration of OSM in Telegram for sharing location would be very nice indeed :+1:

**Comment by oimis** [comment]
Hi, no need to use OSM: Telegram-FOSS should be simply patched to use [android.location](http://developer.android.com/reference/android/location/package-summary.html) instead of [Google Location Service](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary).

**Comment by Ecron** [comment]
@oimis Google say in that link:
>**This API is not the recommended method for accessing Android location.**
The Google Location Services API, part of Google Play services, is the preferred way to add location-awareness to your app. It offers a simpler API, higher accuracy, low-power geofencing, and more. If you are currently using the android.location API, you are strongly encouraged to switch to the Google Location Services API as soon as possible.

I don't know why but they don't recommend that API... Anyway I'd love to be able to send my location through Telegram-FOSS, so any OSM implementation would be very appreciated. Or even a notice when you decide whether or not implement a location solution.

Good work!!

**Comment by oimis** [comment]
@Ecron Google stop supporting that because it want to make Android a closed platform. For other APIs I can understand your reason, but for an API that simply provide a location, not.
Please provide a real reason that API shouldn't be used.
*"OSM implementation would be very appreciated"* why OSM? OSM are **maps**, how this should be related to getting **device's location**? I understand that the sent location could be shown in an OSM viewer, but how the user choose to visualize coordinates aren't a Telegram related thread. Here we are talking about **how** Telegram could get device's location (geo coordinates) to send it to a contact.

**Comment by Bubu** [comment]
I started implementing this and here are a few considerations:

 - Right now this would not need any location related permissions. Location sharing works by parsing shared `geo: ...` data passed from OSMAnd.
 - Sharing a location through OSMAnd produces something like this:

 ``` Location: geo: <lat>,<long>?z=<zoom> http://osmand.net/go?lat=<lat>&long=<long>&z=<zoom>```
This is now interpreted and send as a location message by Telegram.

 - I would like this to work with other map applications, but I don't know if any produce something similar when sharing a location. (I don't have Google Maps on my device and it crashes in the emulator for me.)
So Input here would be appreciated.

 - When clicking on a location message in a Telegram chat it now tries to open it with an installed map application through a ```geo: lat,long?zoom?(Label)``` intent. This works well with OSMAnd and should work with GMaps, but I can't test it.
The label I use right now could be a bit better and could be localized. For now I use: ```"Shared by <chat name>"```

 - The third part of the PR tries to handle the send/attach location button inside Telegram. For now this tries to open a ```geo:``` intent at a hard-coded location. This is not terribly useful but gets you to a map application where you can then select a location to share via Telegram.
I had the following ideas here:
  - Use the current device location to either send directly or open with a geo: intent. Google API's would not be necessary but the location permissions would.
  - Use [osmdroid](https://github.com/osmdroid/osmdroid) mentioned earlier to replicate the original Telegram functionality. On fdroid there is i.e. [OpenBikeSharing](https://f-droid.org/repository/browse/?fdid=be.brunoparmentier.openbikesharing.app) which uses it.
  - Just remove/ignore the button?

What do you think?

**Comment by helfio** [comment]
This is absolutly great! It's supposed to be on 3.2.2? I'd like to test it :)

**Comment by Akronix** [comment]
still not working on v3.2.6 :(

**Comment by emunicio** [comment]
Same here

**Comment by Bubu** [comment]
I would like to get at least something in the next version. 
Location sharing will work from osmand and orux maps.
Viewing the shared location works in Osman's and Google maps.

**Comment by Bubu** [comment]
This should be in the next version. (3.4.2)
It doesn't include a way to share a location from telegram. Just from OSMAnd and Orux to Telegram.
But it does show a 'Not implemented' warning when truing to attach a location object.

Also location messages are opened with a geo: intent now, instead of not doing anything.

**Comment by Ecron** [comment]
Great! Can't wait to test it :wink::+1:

**Comment by Bubu** [comment]
It's live now.
Something I noticed only after tagging the release: Location sharing from OSMAnd only works for the newest version (2.2.4) now. I think I can add back support for versions <=2.1 for the next release.

**Comment by Ecron** [comment]
Is the way to share location from OSMAnd going to the Share icon, then Send, then Telegram? It only sends coordinates, "geo:" and link to http://osmand website. Like in any other app like SMS, email and such. Am I missing something?

Opening received location messages with OSMAnd works just awesome, and the warning message also works great :+1:

Thanks for this implementations!!

**Comment by Bubu** [comment]
Which version of OSMAnd are you using?

**Comment by Ecron** [comment]
I just updated to OSMAnd 2.2.4 and tried to share location. The exact text Telegram sends is:

```
Lat: XX.XXXXXX,Lon: Y.YYYYYY
Ubicación: geo:XX.XXXXXX,Y.YYYYYY?z=ZZ
http://osmand.net/go?lat=XX.XXXXXX&lon=Y.YYYYYY&z=ZZ
```

Where X, Y and Z represent my actual location.

**Comment by Bubu** [comment]
Ah! Well it didn't occur to me that this message might be localized.
Telegram checks only for messages containing `Location: geo: ...`
I'll look into making this more generic.

**Comment by Bubu** [comment]
This should be fixed for the next version.

**Comment by Ecron** [comment]
Awesome! Looking forward to test it :smiley:

**Comment by Bubu** [comment]
I submitted these changes upstream, let's see if they get picked up. https://github.com/DrKLO/Telegram/pull/1392

**Comment by Ecron** [comment]
God help us.

**Comment by Bubu** [comment]
Please test again with v3.6.1 :-)

**Comment by Ecron** [comment]
It works perfectly :yum:

**Comment by kirantpatil** [comment]
Hi, I have installed v4.2.1 Telegram client from F-Droid

I tried to share my location and it is sending google map as shown below

![image](https://user-images.githubusercontent.com/1178055/30633420-18b0a58e-9ddb-11e7-860d-7d866f0ce905.jpg)

**Comment by thermatk** [comment]
@kirantpatil I answered you in #116, this is just an image. Under the hood, you send your coordinates, not this

**Comment by kirantpatil** [comment]
@thermatk as @Ecron mentioned in https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/27#issuecomment-176330125, it should display OSM map that is my understanding. 

Dear @Ecron, please correct me if I am wrong here.

**Comment by thermatk** [comment]
You are wrong here. It requests an image from static maps API using your
coordinates, there is no OSM static maps API, no known way to generate
image on device, and since it's just a webrequest no need to replace it

**Comment by kirantpatil** [comment]
@thermatk, thanks.

**Comment by thermatk** [comment]
example:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/4fcc5fbcd7d77f4cbde42462e29565e177eefc29/TMessagesProj/src/main/java/org/telegram/ui/Cells/ChatMessageCell.java#L2824

**Comment by dskopa-softdev** [comment]
Could we use http://staticmap.openstreetmap.de ?

**Comment by thermatk** [comment]
@dskopa-softdev makes no sense. Compared to Google's, this one doesn't use https, so is leaking the location during the request to any kid with a sniffer
