### ISSUE TITLE
Update to 2.7.0

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#29]
Changelog according to the play store:
v. 2.6.1
- Add hashtags easily – recently used hashtags are instantly prompted after you input #
- Added sounds for outgoing and incoming messages in the currently opened conversation (can be disabled in notifications settings)
- Long tap to clear search history for hashtags/gifs/images
- Custom backgrounds now shown in Menu drawer
- Bug fixes and UI improvements

**Comment by Bubu** [comment]
Very interested in the update to 2.7.0:
v. 2.7.0
- Sessions List.
View your active Telegram sessions (on desktop, tablet and mobile devices) and close specific sessions remotely.
- Link Previews.
Get rich link summaries for tweets, YouTube videos, Instagram photos and other content.
- Two-step verification.
Set up an additional password that will be required to log into your Telegram account.

**Comment by stefan-niedermann** [comment]
v. 2.8.0

- Einladungslinks für Gruppenchats
- Intelligente Benachrichtigungen
- Sticker Tab im Emojimenü
- Beschriftungen für Bilder
- Orte in der Umgebung im Standortmenü
- 'Angehört'-Status Sprachnachrichten
- Erweiterterte 'schreibt gerade' Status: schickt Bild, nimmt Audio auf, etc.
- Verbesserter Bildlauf und flüssige Animationen

**Comment by slp** [comment]
Sorry for the late answer. I've been AFK for the last three weeks.

I've just merged v2.8.1 (after removing a new absurd depencency, this time with FourSquare). It should be on F-Droid in a few days.

**Comment by Bubu** [comment]
Thank you very much. The update is available on FDroid. :-)
