### ISSUE TITLE
alternative registration identifier & crawl not

### ISSUE THREAD

**Issue by TameOfGroans** [slp/Telegram-FOSS#30]
For those who neither have- nor tolerate sms texting what other identifier could be used for account registration?  

■ Xmpp Texting JID? 
■ nick? 
■ SIP URI? 

 While I understand how some might deem it beneficial to have app/platform peruse contacts to find peers also using service I shall not be allowing that.  Will there be an option to opt out of contacts crawling in the proximate future?

**Comment by stefan-niedermann** [comment]
Hi,

you should ask this question on https://github.com/DrKLO/Telegram . This is only a fork for f-droid where all proprietary components have been removed.

Regards

**Comment by TameOfGroans** [comment]
Thank you for your prompt response and helpful linkification.

**Comment by TameOfGroans** [comment]
https://github.com/DrKLO/Telegram/issues/987
