### ISSUE TITLE
Update to v. 3.0.1

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#31]
Version 2.9.0 was released in the play store. The source code is apparently not yet in the upstream repository. I opened an issue there: DrKLO/Telegram#1106

**Comment by Bubu** [comment]
Seems to be 2.9.1 now. 
The Code is online now.

**Comment by slp** [comment]
I've just merged and cleaned the changes from v2.9.1

As usual, should appear on FDroid in a few days.

**Comment by Allanitomwesh** [comment]
The play store version is at 3.0.0 now

**Comment by Bubu** [comment]
Upstream is at 3.0.1 now. Code for that version is online now.

**Comment by slp** [comment]
Sync'ed with upstream and tagged as 3.0.1. Should be soon on F-Droid.
