### ISSUE TITLE
Some stickers not visible

### ISSUE THREAD

**Issue by w0rinal** [slp/Telegram-FOSS#32]
Hey guys 
There are some sticker packs which I can't see (vicky stickers, the animals and flags are working). I can add them when someone sent one to me and there are white spaces shown in the stickers tab but I don't see the actual stickers, neither in the stickers tab nor when I click a white space and it's sent. 
I'm only using this version so I can't compare whether it's the same with the official version for Android but when using the windows client they are shown and my friend using an iphone can see them as well. 

Is there anyone having the same problem or am I doing something wrong? 

BTW keep it up, you're doing a good job, guys :)

**Comment by w0rinal** [comment]
Oh my god, forget it. Totally my fault. 
Can be closed

**Comment by Walkman100** [comment]
You can close it yourself, click the close button below the comment box

**Comment by w0rinal** [comment]
It's not hard to spot I'm not a developer, is it? lol
Thank you. There was no close button inside the app.

**Comment by Walkman100** [comment]
> There was no close button inside the app.

There's an app... 0.0

**Comment by w0rinal** [comment]
https://github.com/jonan/ForkHub
