### ISSUE TITLE
Update to 3.1.1

### ISSUE THREAD

**Issue by plumpudding** [slp/Telegram-FOSS#33]
Source is up in Upstream
Do we simply merge it?

**Comment by Bubu** [comment]
Upstream is at 3.1.2. The source is not yet online, but I have opened an issue about it: DrKLO/Telegram#1287.

@slp what's necessary to update the fdroid version? Simply merge upstream?

**Comment by plumpudding** [comment]
Actually merging seems not that simple. I think they changed sth in the location backend.

**Comment by Bubu** [comment]
3.1.2 source is online now.

**Comment by slp** [comment]
Thanks, 3.1.2 should be available by the end of this week.

**Comment by Bubu** [comment]
3.1.2 is not yet online. How does it get updated? Does  the autoupdating feature of fdroid work for Telegram?

(Also 3.1.3 is in the Play Store but no source online yet)

**Comment by frazzmark** [comment]
I've got version 3.1.2 from f-droid now

**Comment by plumpudding** [comment]
Thanks @DrKLO! I received the update too.
