### ISSUE TITLE
Cannot send voice messages longer than ~20s

### ISSUE THREAD

**Issue by aphirst** [slp/Telegram-FOSS#37]
Using Telegram-FOSS 3.1.3 from F-Droid, I am experiencing an issue whereby I am unable to send voice messages longer than 20 seconds (sometimes 21 or 22). I can receive them just fine, and I can send such long messages from the Telegram desktop client. I'm the only person I know IRL using F-Droid, and I'm unwilling to manually install an alternative .apk for Telegram, so have not been able to rule out absolutely everything on my side, but this is a consistent and reproducible problem in my hand.

I'm running CM12.1 (nightly) on a Droid 4 (maserati) but this behaviour also occurs on the same handset running CM11 (stable, September).

If there's any other information I should provide, please just let me know. :smile:

**Comment by aphirst** [comment]
I'd like to report that I'm still experiencing this issue in 3.2.6, though the time-length-cap seems to sometimes extend to as much as about 30s.

**Comment by Bubu** [comment]
Can you check if this issue persists in 3.3.1? This should finally fix all connection issues that where introduced in 3.1.3.

**Comment by aphirst** [comment]
@Bubu I can sadly confirm that I am still experiencing the bug in 3.3.1.

**Comment by Bubu** [comment]
I can only say that it works for me. I never use voice messages but I just send some 60-180 s messages.
I can't see how this problem is related to the FOSS version of Telegram. You could maybe try the official Telegram support: https://telegram.org/support.

**Comment by aphirst** [comment]
I had tried that and sadly they insisted that it must have something to do with the -FOSS version.

I just did some more testing and noticed that I *seem* to be able to send long messages to normal contacts, but that the problem appears when I try to send to a group. Perhaps this is something you could also try to reproduce on your end?

**Comment by Bubu** [comment]
I can send longer voice messages to groups without a problem.

**Comment by aphirst** [comment]
I would but that would, as far as I understand, involve me having to install all the Google rubbish. Or, an apk from some utterly untrustworthy website... If I'm wrong and there's a way to do it (safely!) without needing the GApps stuff, I'd love to know.

**Comment by aphirst** [comment]
I haven't been able to test the official version on my own device, but I have access to another identical device with GApps tomorrow and can test it then.

Additionally I have a question that may or may not relate: where does Telegram "store" the recording as it's being made? It wouldn't happen to be in /cache would it?

**Comment by Bubu** [comment]
I just looked at the code and it seems that the recordings are stored either in `/sdcard/Android/data/org.telegram.messenger/cache/` or in `/data/data/org.telegram.messenger/cache/` depending on the access rights to the first(?).

**Comment by Bubu** [comment]
Closing as this is very likely not related to this fork.
