### ISSUE TITLE
Update to 3.2.0

### ISSUE THREAD

**Issue by volnes** [slp/Telegram-FOSS#38]
- Introducing Channels – a great new way to broadcast your messages to unlimited audiences (replaces old Broadcasts).

**Comment by Bubu** [comment]
Update to 3.2.2 is online upstream.

**Comment by slp** [comment]
I've just tagged version 3.2.2. As usual, should be on FDroid in a few days.

**Comment by eevee** [comment]
I think you reopened this ticket by accident  :)

**Comment by slp** [comment]
3.2.2 is already on FDroid, closing issue.
