### ISSUE TITLE
Prebuilt libraries in TMessagesProj/jni/boringssl/lib

### ISSUE THREAD

**Issue by krt16s** [slp/Telegram-FOSS#40]
F-Droid scanner says:

````
ERROR: Found static library at TMessagesProj/jni/boringssl/lib/libcrypto_armeabi-v7a.a
ERROR: Found static library at TMessagesProj/jni/boringssl/lib/libcrypto_x86.a
ERROR: Found static library at TMessagesProj/jni/boringssl/lib/libcrypto_armeabi.a
Could not build app org.telegram.messenger due to BuildException: Can't build due to 3 errors while scanning
````

**Comment by mvdan** [comment]
And if the files are removed, the NDK build doesn't work.

**Comment by slp** [comment]
Damn, I saw those files after the merge, but completely forgot about them afterwards. I'll try to find a solution.

**Comment by slp** [comment]
Are FDroid build servers expected to provide tools like cmake, ninja and go? boringSSL requires such tools. If that's not the case, I'll have two options, (externally?) forking boringSSL to replace its toolchain (and pregenerate some files which are created by golang scripts), or backporting tgnet to openSSL.

**Comment by Bubu** [comment]
@slp: Did you manage to build the library locally? Upstream did not include any build commands for it. I managed to get armeabi-v7a and ameabi to work following this directions: https://boringssl.googlesource.com/boringssl/+/master/BUILDING.md#Building-for-Android
But the x86 target does not work yet.

**Comment by Bubu** [comment]
This is very strange: [TMessagesProj/jni/tgnet/Datacenter.cpp](https://github.com/slp/Telegram-FOSS/blob/f51a844963b67ae7b6a311dbf98ee9d1eb39511e/TMessagesProj/jni/tgnet/Datacenter.cpp) uses some AES_ige_* functions which are in [TMessagesProj/jni/boringssl/crypto/aes/aes_ige.c](https://github.com/slp/Telegram-FOSS/blob/f51a844963b67ae7b6a311dbf98ee9d1eb39511e/TMessagesProj/jni/boringssl/crypto/aes/aes_ige.c) but nor in any upstream boringssl version. They are however present in openssl.
So maybe building against openssl is indeed the better approach?

**Comment by slp** [comment]
@Bubu I've managed to build a static libcrypto.a using the CMake files from the original project, fiddling with them a bit. Problem is, as I mentioned before, this requires tools not included in the NDK (cmake, ninja and go).

I've also tried linking against OpenSSL-GP, already included as srclib in FDroid, but there're some symbols missing, since the API differs a little from boringSSL. Anyway, it should be possible to backport the JNI code to use the first one, if we determine that FDroid build server shouldn't provide the tools required by boringSSL.

**Comment by slp** [comment]
I've replaced boringSSL with a recent version (1.0.1p) of OpenSSL, which is way easier to build with the NDK toolchain. https://github.com/slp/Telegram-FOSS/commit/1dbecb3aa75a934508d8ee9a195f4978f0f9c764

**Comment by Bubu** [comment]
Does it make sense to include the openssl library as a git submodule? But that would probably not work well with the ndk build files. So we need to update openssl manually everytime there is a new version.

Btw. I have no experience working with openssl, why 1.01 and not 1.02?

**Comment by slp** [comment]
@Bubu 
> Btw. I have no experience working with openssl, why 1.01 and not 1.02?

That's just me being a little conservative. I think boringSSL was forked from 1.0.1 series.
