### ISSUE TITLE
Third party maven repo

### ISSUE THREAD

**Issue by mvdan** [slp/Telegram-FOSS#41]
In particular, `http://dl.bintray.com/amulyakhare/maven`. Why is a third party maven repo required? If the library isn't available in jcenter/mavenCentral, you can vendor it.

**Comment by slp** [comment]
Well, I've just followed the instructions from its README.md. Anyway, it's available in jcenter, so I'll just switch repos.

**Comment by mvdan** [comment]
SGTM

**Comment by slp** [comment]
Done: https://github.com/slp/Telegram-FOSS/commit/59c4b8fef2bbfeb9d35277720cf7f3ba91459a0a
