### ISSUE TITLE
Document differences from official client

### ISSUE THREAD

**Issue by tremby** [slp/Telegram-FOSS#43]
Rather than just saying "FOSS-friendly", it'd be nice if the readme explained outlined the specific differences between the official client and this fork.

It'd also be good to say if it's available as a binary anywhere (apk or from the Play store, etc).

**Comment by stefan-niedermann** [comment]
its available on f-droid app store: https://f-droid.org/repository/browse/?fdid=org.telegram.messenger

**Comment by Bubu** [comment]
From the fdroid blurb, maybe put that in the repository readme:

Several proprietary parts were removed from the original Telegram client, including Google Play Services for the location services and HockeySDK for self-updates. Push notifications through Google Cloud Messaging and the automatic SMS receiving features were also removed.

**Comment by Bubu** [comment]
I updated the readme to include this. Also it now has a link to the fdroid build.
