### ISSUE TITLE
URLs are not displayed as links in 3.2.2

### ISSUE THREAD

**Issue by haary** [slp/Telegram-FOSS#46]
Since version 3.2.2 Telegram seems no longer recognize URL schemes. URLs are presented as normal text. The preview feature is also gone.

**Comment by Bubu** [comment]
Yes, I can confirm. Bu the link preview gets generated just not displayed in the foss version.
Upstream Telegram works though.

**Comment by Allanitomwesh** [comment]
Thought it was just me. Can confirm as well. Also affects hashtags (they aren't blue,so can't be clicked) and bot commands (the command happens but the command itself isn't blue)

**Comment by Bubu** [comment]
This seems to be related to #36. After reinstalling Telegram again link previews and url handling works again.

**Comment by Allanitomwesh** [comment]
Reinstalling huh? I'll give it a try

**Comment by geileszeuch** [comment]
I have the same problem here since 3.2.2. Sadly, I cannot check if this a Telegram-Foss problem only or comes directly from upstream.

**Comment by Bubu** [comment]
I found what went wrong. Emoji,replaceEmoji has the side effect of converting a CharSequence into a SpannableString.

**Comment by Allanitomwesh** [comment]
Reinstalling didn't work for me.

**Comment by slp** [comment]
@Bubu Good catch! PR merged.

**Comment by sevan6** [comment]
Would this also fix the #hashtags that are not working anymore?

**Comment by Bubu** [comment]
Yes, they use the same mechanism.

**Comment by Bubu** [comment]
Fixed in new version

**Comment by beerisgood** [comment]
3.2.6 from F-Droid have the same problems. (i upgrade from 3.1.3)
