### ISSUE TITLE
Connection problems since 3.1.3 (included)

### ISSUE THREAD

**Issue by 0-wHiTeHand-0** [slp/Telegram-FOSS#48]
Since version 3.1.3 I am having a lot of connection issues. Sometimes it doesn't connect to the telegram servers, but I always have problems with receiving new messages (I get them 30 or 1 minute later, when with my official telegram desktop client I get them immediately). I must restart the application if I want to read the new messages.
I have checked it in Android 4.4.4 and 4.2.2 getting same results. Now I have the last telegram version (3.2.2), but it still have the same issues.

**Comment by Bubu** [comment]
Duplicate of #36.
