### ISSUE TITLE
Update to version 3.2.6

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#51]
Upstream sources are finally online.
I can try to get the emoji one support working. But it will be a few days until I can look into it.

**Comment by sevan6** [comment]
Hi there,

Any plan to update to upstream version?

I keep using the FOSS (F-Droid) version in spite of the regressions (URL, search, hashtags not working, emojis).

I know it can be a lot of work, it's just to know if something is planned ^^

Sevan

**Comment by slp** [comment]
Hi @sevan6 

I'd like to release an update version this weekend. I'll be working on restoring the BackgroundService to fix the problem with delayed messages. I'll take a look on the other issues too, but since I find hard to reproduce them, can't make any promises :-/

Sergio.

**Comment by sevan6** [comment]
Thanks @slp !

**Comment by slp** [comment]
This took a while, since the last merge caused a major breakage on the Emoji code. But its working fine now, and should be on FDroid in a few days, as usual.

**Comment by jomo** [comment]
Thank you!

**Comment by Bubu** [comment]
Update is live on fdroid.

**Comment by Allanitomwesh** [comment]
Telegram 3.4 for android is out with inline bots and gif updates, just a heads up
