### ISSUE TITLE
Cannot see or join channels

### ISSUE THREAD

**Issue by haary** [slp/Telegram-FOSS#54]
Channels where introduced in Telegram 3.2.0. However, I am not able to see or join channels in 3.2.6. When I click on a channel at tchannels.me in the browser telegram opens but then loads forever.

**Comment by helfio** [comment]
Probably uninstall & install resolves this.

**Comment by haary** [comment]
That does the trick, thanks.

**Comment by coin001** [comment]
I have nor join group channel so please activate my channel
