### ISSUE TITLE
Be able to reject secret chats

### ISSUE THREAD

**Issue by xavihernandez** [slp/Telegram-FOSS#58]
Hi,

It would be good to add possibility to user to reject a chat.
Imagine you have a mobile phone, a tablet, and even a telegram desktop client supporting secret chats (e.g. Cutegram). If someone wants to start a secret chat, mobile phone will automatically accept the secret chat, and therefore if you want to use your tablet, you cannot if mobile phone has caught secret chat deman first. Only way for you to have a secret chat from your tablet, is to start it from your tablet... but hey, imagine your recipient has several devices too... I'll let you conclude this is a no-end loop.

Then, I think a "Accept" and a "Reject" button should be good to be able to accept or reject the secret chat

What do you think guys?

**Comment by Bubu** [comment]
I think that is a feature that should be included in the upstream client. This is only the repository for the foss friendly fork of Telegram.
Maybe try their support: https://telegram.org/support

**Comment by xavihernandez** [comment]
@Bubu I won't lie, I was aware that feature was needed in upstream, and not here. But I didn't find the "Issues" part in their repository... Then I have decided to post here, my bad ;p.

Will try the link you gave me.

**Comment by Bubu** [comment]
Yeah issues were closed upstream. Another option that is supposed to work is contacting them via twitter.

**Comment by xavihernandez** [comment]
Thanks @Bubu will also try @ Twitter.

**Comment by Akronix** [comment]
hmm aren't we going to add new features to telegram android app which upstream version lacks of? why??

**Comment by xavihernandez** [comment]
@Akronix this feature needs to be added upstream, and will have to be merged into this fork.
If upstream refuses this enhencement, Telegram-FOSS may want it anyway, and may add it. But first it must be asked/pull requested in upstream.

**Comment by Akronix** [comment]
Yes, but, sadly, Android upstream doesn't seem to care about users requests. Why has they disabled issues on the github repo? they also don't take care about the pull requests sent to them. Furthermore, I haven't seen any alternative communication channel to convey our demands to them: mailing list, telegram group, bugtracker, nothing of that... and I wouldn't count Twitter as one.
Maybe their own app built-in support but I don't know if they really listen to it since it's done by volunteers.
It could wiser to take this repo as a real fork and start doing things independently upstreams does or not.

**Comment by xavihernandez** [comment]
@Akronix I get your point. I have sen a message @ Twitter and by mail. As you said, I have received no answer.
Well, this way to implement thing is under maintener responsibility I guess.

**Comment by Bubu** [comment]
@akronix: the more things we do different from upstream, the more maintenance effort this fork is going to take. It's always a tradeoff.

You are welcome to send a patch. You can also send it upstream. It might still get merged.

**Comment by Akronix** [comment]
Yes, I'm aware of that.
I wanted to point out if we're going to close any issue that should be implemented on upstream, or rather we're going to work on them independently from upstream (specially if they don't take care about it) and maybe later send a PR to them. Perhaps we should set a policy about this.

I'm not currently working on a patch, unfortunately I have no enough time.
