### ISSUE TITLE
Too many wakelocks and battery drain

### ISSUE THREAD

**Issue by helfio** [slp/Telegram-FOSS#59]
Hi I'm experiencing a lot of wakelocks lately. I'm running last version available on F-Droid over CM13 on Moto G 2013 (Falcon). I know this is related to already closed #36 but I think a couple of wakeups each minute it's kind of too much (see second pic). I don't know if this is the mininum to notification system keeps itself working.

Also as you can see on the last pic, the time the phone is awake is way greater than the time is the screen on.

Does anybody else is experiencing this? I can provide any other logs needed.

![screenshot_20151218-142259](https://cloud.githubusercontent.com/assets/9520033/11897926/041a9094-a594-11e5-9e9f-962f15f12c28.png)
![screenshot_20151218-142308](https://cloud.githubusercontent.com/assets/9520033/11897927/041b8dd2-a594-11e5-9d1a-2131fb54e1a1.png)
![photo_2015-12-18_14-30-30](https://cloud.githubusercontent.com/assets/9520033/11897928/041cec54-a594-11e5-954e-938f672e9c12.jpg)

**Comment by Bubu** [comment]
I don't have much experience with analyzing battery usage. But I just installed the BetterBattery app and will monitor on my phone.
Right now I only have the CPU frequency stats for the last ~200 hours. This shows:
 - 76% deep sleep
 - 14% on but lowest frequency (I think this should roughly corresponds to phone awake but no user interaction(?))
 - 8% max frequency.

Which looks actually a lot better than your stats? But then again most of the time I have my phone in aeroplane mode for ~8h a day.

**Comment by Streetwalrus** [comment]
I'm experiencing the same issue on my Nexus 4 running my own builds of CM13.
On a side note the official source tree does not seem to have doze mode enabled for your device. I do have it enabled on mine though, but I have Telegram exempted from it to allow notifications through.

The upstream reaction to the excessive battery drain from their own notification service was simply to implement GCM which is not acceptable in our case, at which point they stopped caring about it.

I'll take a quick look at it but I have no idea how all of this works so don't expect a fix from me.

**Comment by helfio** [comment]
I just flashed CM12.1 for testing. A couple of days I'll post stats. Maybe it's because of early state of CM13 and not telegram Foss fault.

**Comment by helfio** [comment]
I don't see any significant difference with Lollipop:
![screenshot_2015-12-20-12-44-53](https://cloud.githubusercontent.com/assets/9520033/11917819/32751718-a718-11e5-8cbc-c1331d35fd34.png)
![screenshot_2015-12-20-12-44-47](https://cloud.githubusercontent.com/assets/9520033/11917820/3276c450-a718-11e5-94d0-cce697bbf925.png)
![screenshot_2015-12-20-12-44-42](https://cloud.githubusercontent.com/assets/9520033/11917818/32662d0c-a718-11e5-88b3-f99d58116838.png)

**Comment by Bubu** [comment]
I cannot get the BetterBattery app to work. It doesn't show any stats for me. (It did at some point show partial stats. But I can't get it to show me anything again.)

**Comment by helfio** [comment]
I suppose you installed like a system app/ flashed the zip, right?

**Comment by Bubu** [comment]
I installed from fdroid and gave it root access in it's preferences. That is apparently not enough?

**Comment by helfio** [comment]
On Android 4+ or so, you need an upgraded version because Google changed something related to battery permissions. You can download any updated version from attachted files of this post: 
http://forum.xda-developers.com/showpost.php?p=15869886&postcount=2
and then follow the steps the apps shows you

**Comment by xavihernandez** [comment]
@Bubu  Easier way is to place the apk in /system/priiv-app/, chmod to 644, and rebot your phone.

**Comment by monojp** [comment]
Hi, I also see that a huge amount of wakelocks is produced by Telegram. On the other hand I also understand why.
BTW "Wakelock Detector" is also a good tool to analyze those http://forum.xda-developers.com/showthread.php?t=2179651

**Comment by Akronix** [comment]
Could anybody give stats of the official version so we can compare with?

**Comment by monojp** [comment]
This is from my girlfriends device running the official client
![tmp_31639-img_20160122_233322-1206862526](https://cloud.githubusercontent.com/assets/5738896/12524871/a2e6bac6-c160-11e5-812f-2a2cb278dfbe.jpg)

**Comment by slp** [comment]
Comparing against the official client is not fair, as this one delegates the reception of notifications to GCM.

In any case, I'm considering adopting the same wake-up strategy as microG, and just establish a dumb repetitive alarm every 60 secs. It's not as good as our current implementation on the best case scenario, but deals better with the rest.

**Comment by monojp** [comment]
I'm curious. May I ask what the difference between your described upstream and the current solution is?
I do understand that gcm is something completely different and the non-gcm solution is always going to need timers/alarms or smth like that which produces wakelocks.

**Comment by Bubu** [comment]
Starting with version 3.4.2 if you switch off "Smart push" in the options you should get exactly one alarm/min, which is better than the 2-3/min before.

But I wonder if it would be enough to wake up the phone much less often. 
I looked a bit at [K9mail](https://github.com/k9mail/k-9) and their push email notification. Their standard setting is to wake up every 24 min. to keep alive the push connection. This works absolutely fine for me but others reported they had to set it to every 6 min.

So my questions would be:
 * Is the basic mechanism even comparable?
 * Would every 24 min. wake up be enough for most cases?
 * Would 6 min be enough for the worst case?

I will have a look at their code when I get around to it.

**Comment by xavihernandez** [comment]
@Bubu unfortunately, this 24 min interval is not reliable for everyone.
It is carrier dependant. In my case, for example, my provider kills IDLE connection that is older than 5 minutes. Then my phone has to be awoken every 4-5 minutes maximum in order to keep connection alive.

**Comment by helfio** [comment]
Could be possible to add some kind of 'hidden' entry to modify this IDLE time from settings? This way anyone could adjust the time to fit their needs.

**Comment by helfio** [comment]
Could be possible to add some kind of 'hidden' entry to modify this IDLE time from settings? This way anyone could adjust the time to fit their needs.

**Comment by Bubu** [comment]
Yes, we should definitely make it user configurable. I don't now if it's necessary to hide it somewhere.

**Comment by helfio** [comment]
I don't know if you already tried this, but an idea came to my mind:
Once phone is booted, IDLE time could be from a little value increasing over time and checking if the conection was dropped or not, this way it could stay on the larger value.

**Comment by xavihernandez** [comment]
@helfio this could be a good thing.
Telegram could even tell the user what did it find and set as "max reliable value". And user could overwrite this value if he prefers another one (higher or smaller)

**Comment by monojp** [comment]
I was using the new Telegram today with Smart Push disabled and it kept the phone less often awake according to the wakelock detector app. Will try the same tomorrow but with Smart Push enabled. So Smart Push is using the NetworkAlarm class, right? Wouldn't it conserve even more battery if "setExact" is not used on SDK >= 19 or is that exact alarm needed to keep the connection alive?

**Comment by frazzmark** [comment]
I have x9364 wakelocks with telegram and x200 or so with WhatsApp. I think that's worth something on battery

**Comment by vanitasvitae** [comment]
Battery lasts so much longer with smart push turned off. Yesterday my battery died in 10 hours, then I charged the phone, turned off smart push and now the statistics show 4 days remaining :D

**Comment by vanitasvitae** [comment]
Wakelocks went down to 54 in 10h with 1 min waketime instead of 3 hours and 5400 wakelocks.

**Comment by Hijis** [comment]
Also, discharge caused by wake time more than by times of wakeloks. Here on the screenshot "plus messenger" wake more than 1000 times, but in my tests it has low battery consumption
![screenshot_2016-02-06-16-00-36](https://cloud.githubusercontent.com/assets/17022100/13027630/b8e7392c-d25e-11e5-8011-b5357d1288f1.png)

**Comment by Hijis** [comment]
I decided to write here so as not to produce the essence.
There are one more problem for me: dropped TCP session when Telegram is closed (by swiping out it from recent apps list), so unable to get new message notification, while "Notifications Service" still works. Sometimes somehow TCP session renews, sometimes not. I can't discover what has influence to it. Yup, possible decision is not to close Telegram, but if NService still running, i think, it would be better, if session will renew automatically, or will not fall on close. 
Srry sr trrble engls :confounded:

**Comment by beljebuzz** [comment]
Hi, I'm stuck with Telegram-FOOS version 3.1.2 since this consumption issue appeared in newer versions. I have not tried to compare newer source code against 3.1.2 yet. It seems to me that the Android (CyanogenMod) version is not a variable to consider here, since the issue is present in both my 4.4.4 and 5.1.1 devices (no idea about 6.0).

Let me know if I can help a little more in solving this issue.

**Comment by Hijis** [comment]
New telegram (3.6.1 (756)) works perfect with disabled "smart push", no battery drain, no too many wakelocks!

**Comment by utack** [comment]
3.6.1 causes an alarm/wakeup every minute.
Might be the only option to get messages without "smart push", seems to be effecting battery quite a bit.

**Comment by Bubu** [comment]
@utack ideally we would have something like K9 Mail, which has a configurable idle connection timer. From 1 minute to 60 minutes. I think what works for you is dependent on your mobile provider. Mine works fine with checking in every 24 minutes but others need to refresh the connection every minute.

**Comment by utack** [comment]
How does the other messaging app with the green icon solve that? it only causes a wakeup every 4 minutes, no significant time of wakelocks and all messages are delivered without noticable delay.  
Also, have you looked at [OwnPush](http://forum.xda-developers.com/android/apps-games/future-push-services-ownpush-t3306763), sounds like a pain to integrate initially but a really nice solution

**Comment by vanitasvitae** [comment]
They use (like most messengers) Google Cloud Messaging (which is proprietary) to check for incoming messages.

**Comment by utack** [comment]
New phone, new luck
Absolutely no battery drain or wakelocks for me now, smart push on

**Comment by slp** [comment]
@utack Cool, thanks to letting us know.

**Comment by slp** [comment]
On 3.10.x, NetworkAlarm has been replaced with a simpler repeating Alarm.
