### ISSUE TITLE
Voice message played via ear speaker

### ISSUE THREAD

**Issue by jomo** [slp/Telegram-FOSS#61]
Voice messages are played back via the front/ear speaker (used for phone calls) instead of the main speaker (default for non-call audio). I can barely hear it and naturally increasing the volume doesn't have any effect since it only changes the main speaker volume.

Additionally, my screen turns black while the audio is playing which is probably a specific problem with my phone where the proximity sensor constantly reports something close to it. However, this is usually _only_ happening during phone calls.

**Comment by helfio** [comment]
I cannot replicate this

**Comment by Bubu** [comment]
Neither can I. You should contact Telegram Support: https://telegram.org/support

**Comment by jomo** [comment]
Apparently Telegram uses the front speaker when the proximity sensor reports something close: [MediaController.java#L1311](https://github.com/slp/Telegram-FOSS/blob/c83823dd3f020e66ca0eb598c0e3fd1944f1ce88/TMessagesProj/src/main/java/org/telegram/messenger/MediaController.java#L1311), so that's related to the other issue I'm having.

I guess you can reproduce it if you put your phone next to your ear, but that's not a bug then.
