### ISSUE TITLE
JNI Build

### ISSUE THREAD

**Issue by jlelse** [slp/Telegram-FOSS#65]
How can I build the native libraries?
Building apk works perfectly but it crashes on start because native methods are missing.

**Comment by Bubu** [comment]
Download the android-ndk Then go to the Project directory (./TMessagesProj) and execute ndk-build.
Then re-run the gradle build which packages the native libs into the apk.

**Comment by jlelse** [comment]
How do I execute ndk build with Telegram?

**Comment by Bubu** [comment]
You may want to look here: http://developer.android.com/ndk/guides/ndk-build.html#ifc

Otherwise what exactly is not working for you?

**Comment by conectapb** [comment]
@Bubu unsuccessfully searched the net a step by step tutorial has more, missing only recompile the native libraries

**Comment by g1hostsilvestre** [comment]
What are the libraries that have to create for Apk works
Do you have any specific name? Or just use the ndk

**Comment by Bubu** [comment]
Running `ndk-build` in the TMessageProj directory builds all required native code.

**Comment by g1hostsilvestre** [comment]
because I run ndk-build I must remove the `ndk-build` the TMessageProj directory to run android-studio ???

**Comment by g1hostsilvestre** [comment]
In which file I add to the Telegram Api so for my App ???
--------------------------------------------------------------------------------
Em qual arquivo eu adiciona as Api do Telegram so para meu App???

**Comment by g1hostsilvestre** [comment]
I've done the procedure there "perform ndk-build makes the whole process" do not touch anything else there generate the .apk install the phone when flight opened the message "Sorry! Unfortunately, the App stopped. "Oh shut! What did can is going on? Wrong

Já fiz o procedimento lá de “ executo o ndk-build faz todo o processo   “  não mexo em mais nada ai gero o Apk instalo no celular quando voo abri a seguinte mensagem “ Desculpe! Infelizmente, o App parou.” Ai fecha! Oque pode está acontecendo? De errado

**Comment by Bubu** [comment]
I don't understand what you are saying, sorry.

**Comment by g1hostsilvestre** [comment]
Generate the .apk on Android Studio when I install on mobile weighing error "Sorry! Unfortunately, the App stopped. "
----------

Gero o Apk no Android Studio quando instalo no celular pesagem de erro “ Desculpe! Infelizmente, o App parou.”

**Comment by g1hostsilvestre** [comment]
Error:(71, 1) A problem occurred evaluating project ':TMessagesProj'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by g1hostsilvestre** [comment]
![tele](https://cloud.githubusercontent.com/assets/18726965/14936919/c7a4399a-0ece-11e6-8f29-cd9585848769.jpg)

**Comment by g1hostsilvestre** [comment]
@Bubu 

Could someone help me with this error oh!

-------------------------------------------------------------------------

Error:Execution failed for task ':TMessagesProj:validateDebugSigning'.

    Keystore file C:\Telegram-FOSS-master\TMessagesProj\config\debug.keystore not found for signing config 'debug'.

----------------------------

**Comment by g1hostsilvestre** [comment]
@Bubu 

Hello as I change the name of the folder you saved the files on the phone the original folder and "Telegram" wanted by the name of my Apk

could someone help me ???

Olá como eu mudo o nome da pasta que salva os arquivos no celular a pasta original e " Telegram" queria por o nome do meu Apk

alguém poderia me ajuda???

**Comment by rezamk** [comment]
Hello freinds,

I opened TMessagesProj folder. Then launch ndk-build file from my ndk folder. and rebuild project in android studio. But the problem is not resolved.

I do not know anything about ndk. But download android-ndk and import telegram source to android studio. Now explain step by step what to do? Very easy for a beginner to use the ndk.

Thank you.
