### ISSUE TITLE
Telegram 3.4 

### ISSUE THREAD

**Issue by telegra** [slp/Telegram-FOSS#66]
Please Update to the New Version,
because with our old Version the new Gifs are not working(Gif Stickers...)

**Comment by Bubu** [comment]
There is no code available for the 3.4 version yet.

**Comment by Peque** [comment]
It seems there is now another ["bulk" source update available (3.4.2)](https://github.com/DrKLO/Telegram/commit/2114024ab1d9cf209916bcdb3a4a7d44e51a3b0c).

**Comment by Peque** [comment]
@slp BTW, did you try to contact Telegram in order to fund this project?

**Comment by slp** [comment]
I've just started working on this, but it'll take some time. Upstream has added ffmpeg's libav in binary-only form (yes, again). So now I need cherry pick the sources, and write an Android.mk to be able to build it with ndk-build.

**Comment by slp** [comment]
@Peque No, and I doubt they would be interested. They already have the upstream version, which is "just enough free" for them.

**Comment by Bubu** [comment]
Unfortunately I have very little time at the moment, so I can't be of much help. 
But the libav thing looks very strange. All the header files seem to be there with all other files missing.
I guess this is a mistake? But with the disabled issues upstream is hard to notify...

**Comment by Peque** [comment]
@slp I bet they would not support it as another "main" repository. However, perhaps they would gladly pay you a couple of beers for each release... Maybe it is worth a try! :wink:

**Comment by slp** [comment]
It took I while, but I've managed to replace the binary libs with their respective sources, and building everything with ndk-build.

@bubu Could you please give it a try? Works here, but I'd like to have a second opinion before tagging it.

**Comment by Bubu** [comment]
I'll try to do so tomorrow.

**Comment by Bubu** [comment]
Tested and working. 
Builds fine and seems to work fine in the emulator.

**Comment by DrKLO** [comment]
@Bubu it's not a mistake. ffmpeg folder contains build_ffmpeg_android.sh script which can be run from ffmpeg source dir to make the same already compiled binaries. It was easier for me to use this script instead of writing my own makefile.

**Comment by slp** [comment]
Hi @DrKLO 

FDroid forbids to bundle binary libraries (like those libav*.a archives), so everything must be built from sources. I've cherry picked the sources from FFmpeg and extended Android.mk to do the work. If you're interested, I can create a PR for your repo.

**Comment by Bubu** [comment]
Released on fdroid as of now.
