### ISSUE TITLE
version 3.3.2

### ISSUE THREAD

**Issue by Clevero** [slp/Telegram-FOSS#67]
Since there is now no offical android code for the updated version with the new inline bots (version also mentioned here #66 ), can please someone update the repo for working with version 3.3.2?

The code was released [28 days ago](https://github.com/DrKLO/Telegram/commit/512e404db7b917aaf8084541843f641938f3b12c) and I think that must also be done before starting with version 3.4

**Comment by YtvwlD** [comment]
Yesterday, 3.4.2 has been released.

**Comment by Bubu** [comment]
We will skip this one. 3.4.2 will be on fdroid in a few days.
