### ISSUE TITLE
ConnectionsManager Problem

### ISSUE THREAD

**Issue by Hajrieyan** [slp/Telegram-FOSS#69]
Hei, I've Got java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager

What should i do?

Thanks For Help

**Comment by Bubu** [comment]
Did you build the native libraries with the android-ndk?

**Comment by Hajrieyan** [comment]
I think not, would you tell me how to built use ndk?

I have extract ndk but its not give any effect.

Thanks for response

**Comment by Bubu** [comment]
Navigate to the Telegram/TMessagesProj folder and execute: 
`path/to/ndk/ndk-build`
After that rebuild the apk with gradle or Android Studio to include the built libraries into the apk.
