### ISSUE TITLE
Recent emojis are deleted everytime you enter a new chat.

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#70]
I think that's a new issue on 3.4.2.

**Comment by helfio** [comment]
Yeah, I was going to open an issue for this :p

**Comment by Bubu** [comment]
Related to: c4e60b82466880e2cd9c5951848a38f12ae8c3d2?

**Comment by Bubu** [comment]
Should be fixed by 5b58ac958de5c3f6145f4cf2234e8890c0a49822.

**Comment by Bubu** [comment]
@slp what do you think of releasing a 3.4.2a version? Quite a few bugfixes in there already and no new upstream release in sight.
