### ISSUE TITLE
[Question] Gif source code is up-to-date?

### ISSUE THREAD

**Issue by huyduongtu** [slp/Telegram-FOSS#71]
I'm looking for the source code dealing Gif in jni of Telegram.Eg: libavcodec.a, libavformat.a, libavutil.a. They are closed. Fortunately, I've found your project.
My question is whether your code is the same as Telegram's code? Where did you get it or you implement it by yourself?

**Comment by Bubu** [comment]
The libav*s is not Telegram's code. They are libraries from the [ffmpeg](https://www.ffmpeg.org/) project.
Upstream's repo has just a build script rewquiring you to download the sources yourself from the ffmpeg website (https://github.com/slp/Telegram-FOSS/issues/66#issuecomment-175078928).

For better automatic building @slp wrote android makefiles for this repository and added thje required parts of the ffmpeg code.
