### ISSUE TITLE
Happy I-Love-Free-Software-Day!

### ISSUE THREAD

**Issue by vanitasvitae** [slp/Telegram-FOSS#74]
I just wanted to thank all you guys so much for making it possible to use Telegram on a daily basis on a nearly FLOSS-only phone! Keep up the great work! Free Software is only possible due to folks like you <3

**Comment by stefan-niedermann** [comment]
:+1:

**Comment by slp** [comment]
Thanks a lot!

Having a bit of recognition from time to time is really nice.

**Comment by Bubu** [comment]
Thanks! :-)
