### ISSUE TITLE
v3.6.1

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#75]
Waiting for upstream code release...

**Comment by 0x1f415** [comment]
upstream is now at 3.6, so you can update this issue to that version too.

**Comment by Bubu** [comment]
Thanks... still no code released. This is kind of frustrating.

**Comment by jlelse** [comment]
Code released

**Comment by Bubu** [comment]
Thanks. I'll look into it.

**Comment by Bubu** [comment]
@slp seems all ready to go. Do you want to take a look?
I've added a changelog file, containing upstream and our changes. I submitted a merge request to fdroid updating the changelog link.

**Comment by slp** [comment]
@Bubu Looks good to me, great work. I've just applied a minor change to remove the Donations section from README.md. Feel free to tag it for release.

**Comment by Bubu** [comment]
Done. Should be on fdroid in 1-2 days.

**Comment by Bubu** [comment]
Online on fdroid.
