### ISSUE TITLE
Cannot save Image sent as File in Gallery while in Secret Chat

### ISSUE THREAD

**Issue by xavihernandez** [slp/Telegram-FOSS#76]
Hello,

I cannot save Image sent as File (Sedn -> File, instead of Send -> Picture, to keep file in full quality) in Gallery while in Secret Chat. I can do it with normal chats though.

I know this has to be sent to upstream, but we cannot report issue @ Telegram Github.

**Comment by Bubu** [comment]
They revamped the secret chat capabilities in the latest update. So this problem might be fixed automatically once the code for the new version gets pushed.

**Comment by xavihernandez** [comment]
Thanks @Bubu

**Comment by Bubu** [comment]
Can you test with the new version?

**Comment by xavihernandez** [comment]
@Bubu I'll test in a few and get back to you :)

**Comment by xavihernandez** [comment]
Nop, only choices are "Reply", "Save to downloads", "Share" and "Delete".
There is no "Save to Gallery" option.

**Comment by Bubu** [comment]
Okay, at this point can you please report this to the Telegram Support at https://telegram.org/support?
Because now we know it's not a problem of our outdated version. :-)

**Comment by xavihernandez** [comment]
@Bubu ok I'll but their support is not really interactive unfortunately. 
I have already told them about ability to reject a secret chat, and I have never had an answer :) on both Twitter and support.

**Comment by Ecron** [comment]
@xavihernandez as far as I know, Telegram's support is done by a few volunteers and the receive hundreds of questions every day. Maybe they're just overloaded and need some time to reach your question...

**Comment by xavihernandez** [comment]
Oh ok @Ecron I got it ^^

**Comment by Bubu** [comment]
Closing everything not related to this fork.
