### ISSUE TITLE
Emoji not showing up

### ISSUE THREAD

**Issue by Peque** [slp/Telegram-FOSS#81]
Since the 3.6.1 update Telegram is not displaying *any* Emoji in chats:

![00](https://cloud.githubusercontent.com/assets/526577/13634627/0ad3ad1e-e5f7-11e5-99b3-8d58366062f6.png)

However, they seem to be correctly displayed in the chat list (if the last message happens to be an Emoji):

![01](https://cloud.githubusercontent.com/assets/526577/13634650/3215bdae-e5f7-11e5-9972-3fdb0329a379.png)

They are also correctly displayed in the Emoji keyboard:

![02](https://cloud.githubusercontent.com/assets/526577/13634694/88db85b0-e5f7-11e5-888a-a5511a5555ac.png)

Is it only me?

**Comment by Bubu** [comment]
No, I have the same problem... I'll try to fix it asap. (I swear it did work in the emulator... )

**Comment by xavihernandez** [comment]
Lol I think we have posted at same time ;p

**Comment by Peque** [comment]
@xavihernandez indeed! :joy:

**Comment by xavihernandez** [comment]
ahahahah

**Comment by Bubu** [comment]
The emoji replacement code was called in a few instances caused by merging the latest version. This resulted in replacing the unicode codes with empty images. I'll do a few more tests then I'll add a tag with version v3.6.1a.

**Comment by c33s** [comment]
@Bubu do you have an estimate when 3.6.1a will be available on fdroid? haven't updated yet, would wait if you release soon.

**Comment by Bubu** [comment]
I tagged the release just now.
If everything works it should be available sometime tomorrow.

**Comment by xavihernandez** [comment]
Thank you @Bubu

**Comment by c33s** [comment]
i am still at 3.4 with working icons. a friend of mine updated 2 times (3.6.1 yesterday and again 3.6.1 today) still no icons.

should the tag 3.6.1a tag be a seperate package on fdroid or does 3.6.1 get replaced by 3.6.1a?

**Comment by PanderMusubi** [comment]
Thanks for the quick response, looking forward to the fix on F-Droid.

**Comment by Bubu** [comment]
@c33s 3.6.1a will be a new version. It should be available soon. It's already built, but the fdroid index is not yet updated.

**Comment by Peque** [comment]
I can confirm 3.6.1a fixes the issue. Thanks @Bubu! :blush:

**Comment by c33s** [comment]
can also confirm it's fixed with 3.6.1a

**Comment by helfio** [comment]
This is happening on my mother's xperia tipo with android 4.0.4. I wiped everything (I know of), reinstalled old 3.4.2, updated to last 3.6.1a but not success. Emojis doesn't show on chats nor list of chats. Any idea what could I do? 
She's really missing them :p

**Comment by Bubu** [comment]
As far as I know pre Android 4.3 devices don't support emoji at all. You'll have to wait for a replacement (see: #53),

**Comment by helfio** [comment]
OK @Bubu, thank you! :)
