### ISSUE TITLE
Offer black background

### ISSUE THREAD

**Issue by PanderMusubi** [slp/Telegram-FOSS#82]
Please, offer a complete black background in the default backgrounds to choose from. 

Note that users on e.g. Cyanogen the choosing of a background from gallery does not work, this only works when another image viewer other than the one from Cyanogen is installed. This is a known other bug. But since many user want a black background, offer this is in the default selection.

**Comment by Bubu** [comment]
Works for me on CM 12.1 selecting an image from my gallery.

**Comment by PanderMusubi** [comment]
It was a widely reported issue, has nothing to do with Telegram, see e.g. https://forums.oneplus.net/threads/cant-able-to-change-whatsapp-profile-picture-or-group-picture.76715/

Nevertheless, a black background is very welcome. Otherwise I have to download a black PNG from somewhere first.

**Comment by Bubu** [comment]
Can you please suggest this to the upstream Telegram Support at https://telegram.org/support?

**Comment by PanderMusubi** [comment]
Done

**Comment by PanderMusubi** [comment]
I prefer that this feature also comes from upstream. Let's wait for that first.

**Comment by Bubu** [comment]
Closing everything not related to this fork.
