### ISSUE TITLE
Telegram disconnects randomly (very often)

### ISSUE THREAD

**Issue by SparkyCola** [slp/Telegram-FOSS#87]
I've got Version 3.6.1a (from F-Droid-Store) and Telegram seems to disconnect randomly (after a few hours of inactivity) and when it looses it's wifi connection (i don't have mobile internet) for a while.

**Comment by Bubu** [comment]
What does disconnect mean? You don't receive any notifications, when does it start to work again?

Have you tried with  the "Smart Push" Setting on and off, does that make a difference?
For reference see the discussion here: #36

**Comment by SparkyCola** [comment]
I does not receive any notifications and i have to reenter my number and verify it via SMS or another Telegram-Client.

**Comment by SparkyCola** [comment]
Where can I find the "Smart Push" setting?

**Comment by Bubu** [comment]
The first entry under 'Notification Settings'.

But if you get logged out that seems to be an entirely different issue, that should not at all happen on a connection loss.

Normally you stay6 logged in as long, as your client keeps hold of some kind of login token. (Which should be indefinitely?) I have never been logged out even if not using a device for months.

So I don't really know what's happening here, maybe something is cleaning Telegram's data directory from time to time?

**Comment by SparkyCola** [comment]
Maybe it's an issue with the ROM (i wanted to switch anyway) it's BlissPop v3.5 on a Xperia SP (based on Cyanogenmod 12, kernel 3.4.0, unoffical build).

**Comment by Bubu** [comment]
Closing for now, until we find more information this is a bug in Telegram-FOSS.

**Comment by radrow** [comment]
I have this issue too on unrooted galaxy note 20, apk from google play
