### ISSUE TITLE
Info-row in contact profiles

### ISSUE THREAD

**Issue by opensrc1229** [slp/Telegram-FOSS#88]
With version 3.7 suddenly a info row in some contact profiles appears. In the official app this feature doesn't exist obviously. Why is it now available in this fork and how can I add such a info to my profile, there seems to be no option at the moment.

**Comment by Bubu** [comment]
This is not something that is Telegram Foss specific.
I just looked at my contacts and this info section appears only for channels or bots. This is an upstream feature.
