### ISSUE TITLE
Version 3.8.0

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#92]
v. 3.8.0
- Fully redesigned chat screens, optimized colors, beautiful progress bars, revamped attachments.
- Tap on any sticker to view its pack and add it to your collection. Preview and send stickers from the pack preview menu.
- Introducing Bot API 2.0, the biggest update to our bot platform since June 2015. Try out these sample bots to see what's coming your way soon: @music, @sticker, @youtube, @foursquare

Bots can ask for accessing your location now. I guess we should enable the location permission in this version for that to work. More info here: https://telegram.org/blog/bots-2-0
As there is an explicit dialogue prompt asking for your location I don't think this is a privacy problem. (You can always chose not to use these bots. And when you accidentally do you can decline the prompt.)

**Comment by opensrc1229** [comment]
Source code of version 3.8.1 is now online!

**Comment by Bubu** [comment]
Thanks, I'll look into it.

**Comment by Bubu** [comment]
Just wanted to say I'm on it. There have been a lot of changes in the latest release, a lot of merge conflicts in the changes we did regarding push notifications and location sharing.

**Comment by Bubu** [comment]
I pushed a first version. I probably can continue work on this on monday.

Things to look into:
 - Test location sharing from OSMAnd --> Seems to work.
 - Test location sharing to bots, see what happens if this doesn't work. -->I need a bot that implements this.
 - Test opening location messages. --> Need to figure out a new way to get the chat title where it's shared from.  
 - The push service option changed internally in Telegram
  - There is now a Keep-Alive-Service and a Background Connection option.
  - Check what the implications for native code are.
  - Probably fix user displayed strings.

@slp Can you maybe have a look at the push service changes? There were a few changes on the jni side. I.e.: ConnectionsManager.cpp

**Comment by g1hostsilvestre** [comment]
I've done the procedure there "perform ndk-build makes the whole process" do not touch anything else there generate the .apk install the phone when flight opened the message "Sorry! Unfortunately, the App stopped. "Oh shut! What did can is going on? Wrong

Já fiz o procedimento lá de “ executo o ndk-build faz todo o processo “ não mexo em mais nada ai gero o Apk instalo no celular quando voo abri a seguinte mensagem “ Desculpe! Infelizmente, o App parou.” Ai fecha! O que pode está acontecendo? De errado

**Comment by g1hostsilvestre** [comment]
Error:(71, 0) SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
<a href="openFile:C:\Telegram-FOSS-master\TMessagesProj\build.gradle">Open File</a>

**Comment by opensrc1229** [comment]
How are you doing? Any problems with version 3.8.1?

**Comment by Bubu** [comment]
@opensrc1229: Sorry, I have very little time for this right now.

Missing for 3.8 are detailed in the post above. (Someone needs to look over the connection manger changes.)

I haven't started looking at 3.9...

**Comment by Bubu** [comment]
I uploaded the current status as a beta version to my server: [TelegramFOSS-3.8.1-beta.apk](https://cloud.bubu1.eu/index.php/s/GGUDpLq5Syidpjc)

Maybe someone can test this version. The major thing I'm not sure about is the push service changes. It works fine in the emulator, but I'm still trying to find a way to install this as a replacement for the fdroid version on my device. That means without losing all secret chats.

**Comment by flortsch** [comment]
Hello, I tested your apk for half a day so far and it works like a charm. I'll further test it and give feedback.

**Comment by flortsch** [comment]
Okay, the only problem I have found so far is that telegram crashes when you try to share e.g. an image from another app like the galery.

**Comment by c33s** [comment]
is it save to upgrade to [TelegramFOSS-3.8.1-beta.apk](https://cloud.bubu1.eu/index.php/s/GGUDpLq5Syidpjc/download), i also want to prevent to loose my secret chats
