### ISSUE TITLE
Add option to automatically save images to separated galleries

### ISSUE THREAD

**Issue by mcagl** [slp/Telegram-FOSS#96]
If the option that automatically saves images to gallery is True, they all go in the same directory, resulting with one overcrowded directory where it's difficult to search/find a specific image/file.

It could be a better UX to have another option (also a boolean) that saves the photos under a different directory, one per chat/group.

They can be called by username or phone number if they come from a 1 to 1 chat,and by group name if they come from a multiple chat (and then if a user renames the group,this could trigger a rename in the subdirectory too).

**Comment by Ecron** [comment]
Hi @mcagl! As I understand it, this project is to remove any licenses from official Telegram project so it can really considered as Open Source, so implementing additional features is not part of this goal.

Maybe you can suggest these improvements to [Plus Messenger](https://github.com/rafalense/Plus-Messenger) project, or any other Telegram fork :+1:

**Comment by Bubu** [comment]
@Ecron Thanks for the explaining that. Closing this issue.
