### ISSUE TITLE
Version 3.9.0

### ISSUE THREAD

**Issue by Orbitkorbi** [slp/Telegram-FOSS#98]
v3.9.0 is out

- Edit your messages everywhere within 2 days after posting.
- Mention people in groups by typing @ and selecting them from the list — even if they don't have a username.
- Get to your friends faster with the new People list in Search.
- Find inline bot shortcuts in the attachment menu.
- Add chat shortcuts to home screen.

**Comment by digidalla** [comment]
@slp @DrKLO Hello i have tried to run both telegram project and they did run however when they do it crash and says unfortunately, Telegram has stopped please i need some help

**Comment by Bubu** [comment]
@digidalla: Did you build the native libraries? Please see here for more information: #65

**Comment by landry314** [comment]
we are in 3.9.1 now. is someone building this distro?

**Comment by vanitasvitae** [comment]
It would be nice to have a release again. How is the progress on this?

**Comment by Bubu** [comment]
Unfortunately Telegram is broken right now after trying to update form the fdroid version to a self-built one.
I hope I can find some time to work on this tomorrow though.

**Comment by landry314** [comment]
3.10 was just released.

**Comment by landry314** [comment]
I am about to cave and use the Play Store. I really dont want to but I am fiending for those new features. if this project is halted, I'd like to know so I can move on.

**Comment by slp** [comment]
Hi there! I know we're very late on keeping up with upstream, sorry about that!

Due to personal reasons, it was impossible for me to put any time on this. But next week I'll have some free time, and I intend to merge with upstream, review some issues, and release a new version.

**Comment by landry314** [comment]
Thank you so much for your work on this distribution!

**Comment by landry314** [comment]
im afraid if i install the play store version i will lose my data due to a different app id number. can anyone confirm if this is true?

**Comment by vanitasvitae** [comment]
You will lose your data because you have to uninstall Telegram-Foss before installing the PlayStore Version (different signing key)

**Comment by Bubu** [comment]
You will unfortunetely lose secret chat data and settings. Everything else is synced to the cloud.

**Comment by juanito003** [comment]
Hi, please could anyone push update on F-Droid? v3.10.1 is out on Play store and F-Droid is still behind with v3.7.0. I switched many friends and family to Telegram and today I am no longer able to connect.
@slp Dear Sergio, are you in charge for this? Could we count on you, please?
Thank you very much, Muchas gracias for your time and efforts.

**Comment by nextl00p** [comment]
It's already build by F-Droid. Should be available in the repo within a few hours. Looking forward.
https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_8213
https://gitlab.com/fdroid/fdroiddata/commit/efc563634015f9a53af75d5b9681f007b58b35a8

**Comment by vanitasvitae** [comment]
Thats great news :+1:

**Comment by juanito003** [comment]
Wonderful! I did not know it was already done! Thanks.

**Comment by landry314** [comment]
oh praise the coding gods! my prayers have been answered!

**Comment by Peque** [comment]
I works pretty well for me so far. I guess #92 and #102 could be closed as well. :blush:

**Comment by landry314** [comment]
version 3.11 was just released on the play store... now we are behind again!
